language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-2.2.3
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-2.2.3
before_install:
  - gem install bundler
  # Unfortunately, these old versions of octokit, faraday, faraday_middleware 
  # are not found by bundler automatically. Hence a manual installation.
  - gem install faraday_middleware --version 0.9.0
  - gem install faraday --version 0.8.8
  - gem install octokit --version 1.25.0
script: bundle exec rspec spec/*
