language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - jruby-head
  - jruby-19mode
  - rbx-2.2.3
matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: jruby-head
    - rvm: jruby-19mode
    - rvm: rbx-2.2.3
before_install:
  - gem install bundler
  - gem install faraday_middleware --version 0.9.0
  - gem install faraday --version 0.8.8
  - gem install octokit --version 1.25.0
  - gem install rspec --version 2.14.1
script: bundle exec rspec -f d spec/*
