language: ruby
rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - jruby-9.0.5.0
  - rbx-2.5.8
matrix:
  allow_failures:
    - rvm: jruby-9.0.5.0
    - rvm: rbx-2.5.8
before_install:
  - gem install bundler
  - bundle
script: bundle exec rspec spec/*
